server:
  port: 8086

spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/notification_db?authSource=admin
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI}

notification:
  email:
    from: ${EMAIL_FROM}
  seller-stock-alerts-recipient: ${WAREHOUSE_EMAIL}

common:
  security:
    resource-server:
      enabled: false

logging:
  level:
    com.project.notification: INFO
