server:
  port: 8086

spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_INITDB_ROOT_USERNAME:ecommerce}:${MONGO_INITDB_ROOT_PASSWORD:change_me_mongo}@${MONGO_HOST:mongodb}:${MONGO_PORT:27017}/notification_db?authSource=admin
  mail:
    host: ${SMTP_HOST:mailhog}
    port: ${SMTP_PORT:1025}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:http://auth-service:8081/.well-known/jwks.json}

notification:
  email:
    from: ${EMAIL_FROM:noreply@ecommerce.local}
  seller-stock-alerts-recipient: ${WAREHOUSE_EMAIL:warehouse@ecommerce.local}

common:
  security:
    resource-server:
      enabled: false

logging:
  level:
    com.project.notification: INFO
