server:
  port: 8084

spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_INITDB_ROOT_USERNAME:ecommerce}:${MONGO_INITDB_ROOT_PASSWORD:change_me_mongo}@${MONGO_HOST:mongodb}:${MONGO_PORT:27017}/order_db?authSource=admin
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:http://auth-service:8081/.well-known/jwks.json}

# We're providing our own SecurityConfig; common's auto-resource-server is disabled.
common:
  security:
    resource-server:
      enabled: false

logging:
  level:
    com.project.order: INFO
