server:
  port: 8084

spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/order_db?authSource=admin
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI}

# We're providing our own SecurityConfig; common's auto-resource-server is disabled.
common:
  security:
    resource-server:
      enabled: false

logging:
  level:
    com.project.order: INFO
