spring:
  application:
    name: product-service
  config:
    import: optional:configserver:http://config-server:8888
  mongodb:
      uri: mongodb://root:root@mongodb:27017/product_db?authSource=admin