spring:
  mongodb:
    representation:
      uuid: java_legacy
  application:
    name: payment-service
  threads:
    virtual:
      enabled: ${SPRING_THREADS_VIRTUAL_ENABLED:false}
  main:
    keep-alive: true
  config:
    import: optional:configserver:http://config-server:8888
  data:
    mongodb:
      auto-index-creation: true

springdoc:
  api-docs:
    version: OPENAPI_3_0
