server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      enabled: false
      server:
        git:
          uri: https://github.com/dHRvBiyAn1/ecommerce-platform.git
          default-label: feature/auth-service
          search-paths: config-repo
          clone-on-start: true
    
  # ✅ Also disable bootstrap config fetching entirely
  config:
    import: "optional:configserver:"
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true
  instance:
    prefer-ip-address: true